os: osx
language: node_js
node_js: 10
cache:
  directories:
    - node_modules
before_install:
  - brew install imagemagick
  - npm install -g greenkeeper-lockfile
install: npm install
before_script:
  - greenkeeper-lockfile-update
  - node ./test/_bootstrap.js
script: npm test
after_script: greenkeeper-lockfile-upload
after_success: npm run coverage
