name: CI

on:
  push:
    branches: [latest]
  pull_request:
    branches: [latest]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-
      - name: Install dependencies
        run: npm ci
      - name: Prepare repository
        run: node ./test/_bootstrap.js
        env:
          INSTAPAPER_API_KEY: ${{ secrets.INSTAPAPER_API_KEY }}
          INSTAPAPER_API_SECRET: ${{ secrets.INSTAPAPER_API_SECRET }}
          INSTAPAPER_LOGIN_KEY: ${{ secrets.INSTAPAPER_LOGIN_KEY }}
          INSTAPAPER_LOGIN_SECRET: ${{ secrets.INSTAPAPER_LOGIN_SECRET }}
      - name: Run tests
        run: npm test
        env:
          INSTAPAPER_API_KEY: ${{ secrets.INSTAPAPER_API_KEY }}
          INSTAPAPER_API_SECRET: ${{ secrets.INSTAPAPER_API_SECRET }}
          INSTAPAPER_LOGIN_KEY: ${{ secrets.INSTAPAPER_LOGIN_KEY }}
          INSTAPAPER_LOGIN_SECRET: ${{ secrets.INSTAPAPER_LOGIN_SECRET }}
      - name: Report test coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          flag-name: test-node@${{ matrix.node }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          path-to-lcov: ./coverage/lcov.info

  onEnd:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
          path-to-lcov: ./coverage/lcov.info
